# https://github.com/gianlucam76/k8s-cleaner/blob/main/charts/k8s-cleaner
serviceMonitor:
  enabled: true
  namespace: monitoring
  annotations:
    prometheus: monitoring-kube-prometheus-prometheus
    release: monitoring
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
