# https://github.com/bitnami/charts/tree/main/bitnami/keycloak
auth:
  existingSecret: keycloak-secret
  passwordSecretKey: password
extraEnvVars:
  - name: KEYCLOAK_HOSTNAME
    value: "https://keycloak.tail79a5c8.ts.net"
ingress:
  annotations:
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
  enabled: true
  extraTls:
    - hosts:
        - keycloak
  hostname: keycloak
  ingressClassName: tailscale
  tls: true
metrics:
  enabled: true
  prometheusRule:
    enabled: true
  serviceMonitor:
    enabled: true
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
postgressql:
  auth:
    enabled: true
    existingSecret: keycloak-secret
    postgresPassword: "test"
service:
  type: LoadBalancer
