# https://github.com/longhorn/longhorn/tree/main/chart
# global:
#   nodeSelector:
#     node-role.kubernetes.io/control-plane: "true"
defaultSettings:
  defaultDataPath: /storage
service:
  ui:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.81
ingress:
  enabled: true
  ingressClassName: traefik
  host: longhorn.local
metrics:
  serviceMonitor:
    enabled: true
    annotations:
      prometheus: monitoring-kube-prometheus-prometheus
      release: monitoring
