# https://github.com/prometheus-community/helm-charts/tree/kube-prometheus-stack-66.3.1/charts/kube-prometheus-stack
alertmanager:
  alertmanagerSpec:
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
grafana:
  persistence:
    enabled: true
    size: 10Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.k3s
  service:
    type: LoadBalancer
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
kube-state-metrics:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.k3s
    paths: ['/']
prometheusOperator:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
prometheus-node-exporter:
  extraArgs:
    - --collector.disable-defaults
    - --collector.cpu
    - --collector.meminfo
    - --collector.diskstats
    - --collector.filesystem
    - --collector.netdev
    - --collector.netstat
    - --collector.time
    - --collector.uname
    - --collector.vmstat
