# https://github.com/open-webui/helm-charts/tree/open-webui-4.0.6/charts/open-webui
# ns=ollama
ollama:
  ollama:
    gpu:
      enabled: true
      type: 'nvidia'
      number: 1
    models:
      - llama3.2:1b
      - llama3.2:3b
      - moondream:1.8b
      - qwen2.5-coder:1.5b
  runtimeClassName: nvidia
  persistentVolume:
    enabled: true
    size: 30Gi
extraEnvVars:
   - name: OLLAMA_DEBUG
     value: "1"
   - name: ENV
     value: "dev"
   - name: CHROMA_HTTP_HOST
     value: 10.43.14.46
service:
  type: LoadBalancer
persistence:
  size: 15Gi
podLabels:
  app.kubernetes.io/name: open-webui
ingress:
  enabled: true
  class: traefik
  host: open-webui.k3s
  tls: true
  existingSecret: open-webui-tls-secret
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
