# https://github.com/open-webui/helm-charts/tree/open-webui-4.0.6/charts/open-webui
extraEnvVars:
  - name: OLLAMA_DEBUG
    value: "1"
  - name: ENV
    value: "dev"
  - name: CHROMA_HTTP_HOST
    value: 10.43.14.46
ingress:
  class: traefik
  enabled: true
  existingSecret: open-webui-tls-secret
  host: open-webui.k3s
  tls: true
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
ollama:
  ollama:
    gpu:
      enabled: true
      number: 1
      type: 'nvidia'
    models:
      - llama3.2:1b
      - llama3.2:3b
      - moondream:1.8b
      - qwen2.5-coder:1.5b
  persistentVolume:
    enabled: true
    size: 30Gi
  runtimeClassName: nvidia
persistence:
  size: 15Gi
podLabels:
  app.kubernetes.io/name: open-webui
service:
  type: LoadBalancer
