# https://github.com/traefik/traefik-helm-chart/tree/main/v33.0.0/traefik
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
priorityClassName: "system-cluster-critical"
providers:
  kubernetesCRD:
    enabled: true
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - effect: "NoSchedule"
    key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
  - effect: "NoSchedule"
    key: "node-role.kubernetes.io/master"
    operator: "Exists"
